export const REQUEST_POST_SAVE = 'REQUEST_POST_SAVE';
export const POST_SAVE_IN_PROGRESS = 'POST_SAVE_IN_PROGRESS';
export const HANDLE_POST_SAVE_RESPONSE = 'HANDLE_POST_SAVE_RESPONSE';
export const RESTORE_POST_SAVE = 'RESTORE_POST_SAVE';