export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SIGN_UP_IN_PROGRESS = 'SIGN_UP_IN_PROGRESS';
export const HANDLE_SIGN_UP_RESPONSE = 'HANDLE_SIGN_UP_RESPONSE';
export const RESTORE_SIGN_UP = 'RESTORE_SIGN_UP';


export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SIGN_IN_IN_PROGRESS = 'SIGN_IN_IN_PROGRESS';
export const HANDLE_SIGN_IN_RESPONSE = 'HANDLE_SIGN_IN_RESPONSE';
export const RESTORE_SIGN_IN = 'RESTORE_SIGN_IN';

export const SIGN_OUT = 'SIGN_OUT';